env:
  browser: true
extends: 'eslint:recommended'
rules:
  indent:
    - warn
    - 4
    - {SwitchCase: 1}
  linebreak-style:
    - error
    - unix
  no-console:
    - error
    - allow:
        - warn
        - error
  quotes:
    - warn
    - single
  semi:
    - error
    - always
  curly:
    - error
  complexity:
    - warn
    - 10
globals:
    folio: true
    SVG: true
